FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block f5_openstack_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set agent_git_repo = "https://github.com/F5Networks/f5-openstack-agent" %}
{% set agent_tag = "v10.1.0" %}

RUN pip install git+{{ agent_git_repo }}@{{ agent_tag }}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block f5_openstack_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
